import { dir } from "i18next";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.scss";
import { languages } from "../i18n/settings";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
  params: { lng },
}: Readonly<{ children: React.ReactNode; params: { lng: string } }>) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <head />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
